//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account()
        {
            this.calendar_event = new HashSet<calendar_event>();
            this.dosens = new HashSet<dosen>();
            this.mahasiswas = new HashSet<mahasiswa>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public byte active { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
    
        public virtual ICollection<calendar_event> calendar_event { get; set; }
        public virtual ICollection<dosen> dosens { get; set; }
        public virtual ICollection<mahasiswa> mahasiswas { get; set; }
    }
}
