//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class akun
    {
        public akun()
        {
            this.calendar_event = new HashSet<calendar_event>();
            this.pengumumen = new HashSet<pengumuman>();
            this.mahasiswas = new HashSet<mahasiswa>();
            this.jadwal_tidak_kosong = new HashSet<jadwal_tidak_kosong>();
            this.dosens = new HashSet<dosen>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public byte aktif { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public byte peran { get; set; }
    
        public virtual ICollection<calendar_event> calendar_event { get; set; }
        public virtual peran peran1 { get; set; }
        public virtual ICollection<pengumuman> pengumumen { get; set; }
        public virtual ICollection<mahasiswa> mahasiswas { get; set; }
        public virtual ICollection<jadwal_tidak_kosong> jadwal_tidak_kosong { get; set; }
        public virtual ICollection<dosen> dosens { get; set; }
    }
}
