//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jadwal_semester
    {
        public int id { get; set; }
        public System.DateTime tanggal { get; set; }
        public string isi { get; set; }
        public int id_semester { get; set; }
        public Nullable<byte> jenis_skripsi_id { get; set; }
    
        public virtual jenis_skripsi jenis_skripsi { get; set; }
        public virtual semester semester { get; set; }
    }
}
