//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jadwal_tidak_kosong
    {
        public int id { get; set; }
        public string username { get; set; }
        public System.DateTime tanggal_mulai { get; set; }
        public System.DateTime tanggal_selesai { get; set; }
        public string text { get; set; }
        public string description { get; set; }
        public int periode_sidang_id { get; set; }
    
        public virtual akun akun { get; set; }
        public virtual periode_sidang periode_sidang { get; set; }
    }
}
