//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jenis_skripsi
    {
        public jenis_skripsi()
        {
            this.jadwal_semester = new HashSet<jadwal_semester>();
            this.skripsis = new HashSet<skripsi>();
        }
    
        public string id { get; set; }
        public string nama_jenis { get; set; }
    
        public virtual ICollection<jadwal_semester> jadwal_semester { get; set; }
        public virtual ICollection<skripsi> skripsis { get; set; }
    }
}
