//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategori_nilai
    {
        public kategori_nilai()
        {
            this.nilais = new HashSet<nilai>();
        }
    
        public int id { get; set; }
        public Nullable<int> urutan { get; set; }
        public string kategori { get; set; }
        public int bobot { get; set; }
        public string tipe { get; set; }
        public byte jenis_skripsi_id { get; set; }
    
        public virtual jenis_skripsi jenis_skripsi { get; set; }
        public virtual ICollection<nilai> nilais { get; set; }
    }
}
