//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laporan
    {
        public int id { get; set; }
        public string jenis { get; set; }
        public string deskripsi { get; set; }
        public System.DateTime tanggal_pengumpulan { get; set; }
        public int id_skripsi { get; set; }
    
        public virtual skripsi skripsi { get; set; }
    }
}
