//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nilai
    {
        public int id { get; set; }
        public int id_skripsi { get; set; }
        public string jenis { get; set; }
        public double angka { get; set; }
        public Nullable<double> bobot { get; set; }
        public string NIK_pengisi { get; set; }
        public int isSidang { get; set; }
    
        public virtual dosen dosen { get; set; }
        public virtual skripsi skripsi { get; set; }
    }
}
