//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class periode_sidang
    {
        public periode_sidang()
        {
            this.jadwal_tidak_kosong = new HashSet<jadwal_tidak_kosong>();
        }
    
        public int id { get; set; }
        public int semester_id { get; set; }
        public string tipe_sidang { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<jadwal_tidak_kosong> jadwal_tidak_kosong { get; set; }
        public virtual semester semester { get; set; }
    }
}
