//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class semester
    {
        public semester()
        {
            this.jadwal_semester = new HashSet<jadwal_semester>();
            this.periode_sidang = new HashSet<periode_sidang>();
            this.skripsis = new HashSet<skripsi>();
            this.topiks = new HashSet<topik>();
        }
    
        public int id { get; set; }
        public string periode_semester { get; set; }
        public byte isCurrent { get; set; }
    
        public virtual ICollection<jadwal_semester> jadwal_semester { get; set; }
        public virtual ICollection<periode_sidang> periode_sidang { get; set; }
        public virtual ICollection<skripsi> skripsis { get; set; }
        public virtual ICollection<topik> topiks { get; set; }
    }
}
