//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sidang
    {
        public int id { get; set; }
        public System.DateTime tanggal { get; set; }
        public int ruang { get; set; }
        public int id_skripsi { get; set; }
        public string description { get; set; }
        public string penguji1 { get; set; }
        public string penguji2 { get; set; }
    
        public virtual dosen dosen { get; set; }
        public virtual dosen dosen1 { get; set; }
        public virtual ruang ruang1 { get; set; }
        public virtual skripsi skripsi { get; set; }
    }
}
