//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class skripsi_automationEntities1 : DbContext
    {
        public skripsi_automationEntities1()
            : base("name=skripsi_automationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> accounts { get; set; }
        public DbSet<bimbingan> bimbingans { get; set; }
        public DbSet<calendar_event> calendar_event { get; set; }
        public DbSet<dosen> dosens { get; set; }
        public DbSet<jadwal_kosong> jadwal_kosong { get; set; }
        public DbSet<laporan> laporans { get; set; }
        public DbSet<mahasiswa> mahasiswas { get; set; }
        public DbSet<nilai> nilais { get; set; }
        public DbSet<pengumuman> pengumumen { get; set; }
        public DbSet<pesanan_bimbingan> pesanan_bimbingan { get; set; }
        public DbSet<revisi> revisis { get; set; }
        public DbSet<sidang> sidangs { get; set; }
        public DbSet<skripsi> skripsis { get; set; }
    }
}
