//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyek_Informatika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class topik
    {
        public topik()
        {
            this.skripsis = new HashSet<skripsi>();
        }
    
        public int id { get; set; }
        public string judul { get; set; }
        public string deskripsi { get; set; }
        public string keterangan { get; set; }
        public string NIK_pembimbing { get; set; }
        public int id_semester { get; set; }
    
        public virtual semester semester { get; set; }
        public virtual ICollection<skripsi> skripsis { get; set; }
        public virtual dosen dosen { get; set; }
    }
}
